# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d58544efb1ab5972ad743761b002ca7965a77f4f8c2bbb86bf93dc63e1b2e2283a7a9e024fd1af982a8ed4b0713523acbb880ded8c572cca3679b38d2788eb4

test:
  secret_key_base: 6643ea75e4bfc1f0f92ebd8c3bedf726306374439566da30a30dc6e5aa0bedc74f433347ac908a4d3ee207e7a03b40eaf8f5715a71f45bf2a3b869ff98b0439d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
